work around some compilation issues
Old GCC:
    NLPSolverGAMS.cpp: In member function 'virtual SHOT::E_NLPSolutionStatus SHOT::NLPSolverGAMS::solveProblemInstance()':
    NLPSolverGAMS.cpp:201:34: sorry, unimplemented: non-trivial designated initializers not supported
             .switchhandle = fromGAMS };

MSVC:
    NLPSolverGAMS.cpp(196): error C7555: use of designated initializers requires at least '/std:c++latest'

                                      ^